[package]
name = "bitpiece"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["bitpiece_macros"]

[dependencies]
bitpiece_macros = { path = "bitpiece_macros", version = "0.1.0" }
paste = "1.0.15"
